## 프로미스의 등장

### 기존의 비동기 처리 방식 : 콜백 패턴

> 🔎 비동기 함수의 동작 과정
>
> 비동기 함수는 함수 내부의 비동기 코드가 완료되지 않았다해도 기다리지 않고 즉시 종료된다.
> 비동기 함수 내부 로직은 태스크 큐에 저장되어 대기하다가 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.
> 즉, 비동기 코드는 비동기 함수가 종료된 이후에 실행된다!
>
> 이는 비동기 코드의 처리 결과를 외부로 반환하거나 상위 스코프에 변수에 할당해도 기대한대로 동작하지 않는 이유다.

위의 이유로 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.
이때 비동기 함수를 범용적으로 사용하기 위해 **후속 처리를 수행하는 콜백 함수를 인자로 전달**하는 것이 일반적이다.
이를 `콜백 패턴` 이라 한다.

### 콜백 패턴의 문제점1 : Callback Hell

이처럼 후속 처리를 수행하는 콜백 함수가 처리 결과를 가지고 또 다시 비동기 함수를 호출해야 한다면
(여러 비동기 작업을 순차적으로 수행해야할 때)

콜백 함수의 호출이 중첩되어 복잡도가 높아지는 현상이 발생하는데, 이를 `콜백 헬` 이라 한다.

<p align="center">
<img src="https://user-images.githubusercontent.com/62097867/209919645-30d7c89c-c70a-40cd-80bd-80e01273e35e.png" width="400px" />
</p>

### 콜백 패턴의 문제점2 : 에러 처리의 한계

```jsx
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다.
  console.error("캐치한 에러", e);
}
```

위의 예제에서 콜백 함수가 실행되어 에러가 발생되어도 catch 블럭에서 캐치되지 않는다.

1. setTimeout이 호출되면 setTimeout 함수의 실행 컨텍스트가 생성되어 콜 스택에 푸시되어 실행된다.
2. setTimeout은 비동기 함수이므로 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택에서 제거된다.
3. 이후 타이머가 만료되면 setTimeout의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비었을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.
4. 콜백 함수에서 에러가 발생될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태이므로 에러가 catch 블럭에서 캐치되지 않는다. 에러는 호출자 방향 (콜 스택의 아래 방향)으로 전파되기 때문에

> ES6에서 도입된 프로미스는 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.

## 프로미스

비동기 처리에 사용되는 객체로 비동기 처리 상태와 결과를 관리한다.

### 프로미스의 생성

Promise 생성자 함수를 통해 Promise 객체를 생성한다.
Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는다.

- 비동기 처리 성공시 `resolve` 함수 호출
- 비동기 처리 실패시 `reject` 함수 호출

```jsx
const promise = new Promise((resolve, reject) => {
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

### 프로미스의 상태 정보

생성된 직후의 프로미스는 기본적으로 `pending` 상태이며,
**이후의 상태는 `resolve`, `reject` 함수를 호출하는 것으로 결정**된다.

| state     | 의미                                  | 상태 변경 조건                   |
| --------- | ------------------------------------- | -------------------------------- |
| pending   | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected  | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

settled 상태는 fulfilled 또는 rejected 상태와 상관없이 pending이 아닌 상태로 비동기 처리가 수행된 상태를 말한다.

### 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백함수가 선택적으로 호출된다.
- 이때 호출되는 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.
- 모든 후속 처리 메서드는 프로미스를 반환하며 비동기로 동작한다.

**`Promise.prototype.then`**

then 메서드는 두 개의 콜백 함수를 인수로 전달받는다.

```jsx
/**
 * 첫번째 콜백 함수
 * - 비동기 처리가 성공했을 때 호출되는 콜백 함수
 * - 프로미스가 fulfilled 상태가 되면 호출된다. (resolve 함수가 호출된 상태)
 * - 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
 *
 * 두번째 콜백 함수
 * - 비동기 처리가 실패했을 때 호출되는 콜백 함수
 * - 프로미스가 rejected 상태가 되면 호출된다. (reject 함수가 호출된 상태)
 * - 콜백 함수는 프로미스의 에러를 인수로 전달받는다.
 */
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

then 메서드는 언제나 프로미스를 반환한다.
만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고,
프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 반환한다.

**`Promise.prototype.catch`**

catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다.

프로미스가 reject 상태인 경우에만 호출된다.

```jsx
new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>
  console.log(e)
); // Error: rejected
```

then(undefined, onRejected)와 동일하게 동작한다.

```jsx
new Promise((_, reject) => reject(new Error("rejected"))).then(undefined, (e) =>
  console.log(e)
); // Error: rejected
```

> **💡 프로미스의 에러 처리시 catch 메서드 사용 권장**
>
> then 메서드의 두번째 콜백 함수는 첫번째 콜백 함수에서 발생한 에러를 캐치하지 못한다.
> catch 메서드는 비동기 처리에서 발생한 에러와 catch 이전의 모든 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.

**`Promise.prototype.finally`**

finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다.

프로미스가 성공(fulfilled) 또는 실패(rejected)와 상관없이 무조건 한 번 호출된다.

## 프로미스 체이닝

후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다.
이를 프로미스 체이닝(Promise Chaining)이라 한다.

```jsx
/** GET 요청을 통해 응답받은 데이터(userId)를 사용하여 또다시 GET 요청을 한다. 콜백 헬 발생 */

get(`${url}/posts/1`, ({ userId }) => {
  get(`${url}/users/${userId}`, (userInfo) => {});
});

/** 프로미스를 사용해 콜백 헬 개선 */

promiseGet(`${url}/posts/1`)
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
/**
 * - 1번 then 메서드의 콜백 함수는 promiseGet 함수가 반환한 프로미스가 resolve한 값(id가 1인 post)를 인수로 전달받고, 콜백 함수가 반환한 프로미스를 반환한다.
 * - 2번 then 메서드의 콜백 함수는 1번 then 메서드가 반환한 프로미스가 resolve한 값(post의 userId로 취득한 user 정보)를 인수로 전달받고, 콜백 함수가 반환한 값(undefined)을 암묵적으로 resolve하여 생성한 프로미스를 반환한다.
 * - catch 메서드의 콜백 함수는 promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값을 인수로 전달받고, 콜백 함수가 반환한 값(undefined)를 암묵적으로 resolve하여 생성한 프로미스를 반환한다.
 */
```

```jsx
/** ES8의 async/await을 사용해 가독성 개선 */

(async () => {
  const { userId } = await promiseGet(`${url}/posts/1`);
  const userInfo = await promiseGet(`${url}/users/${userId}`);
  console.log(userInfo);
})();
```

## 프로미스의 정적 메서드

**`Promise.resolve` / `Promise.reject`**

이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.
인수로 전달받은 값을 resolve/reject하는 프로미스를 생성한다.

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]
```

```jsx
// 위의 예제와 동일하게 동작
const resolvedPromise = new Promise((resolve) => resolve([1, 2, 3]));
resolvedPromise.then(console.log); // [1, 2, 3]
```

**`Promise.all`**

- 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고,
  전달받은 프로미스가 모두 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.

- 전달받은 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료한다.

다음과 같이 세 개의 비동기 처리가 있을 때

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));
```

순차적으로 처리하면 약 6초가 소요된다.

```jsx
const res = [];
requestData1()
  .then((data) => {
    res.push(data);
    return requestData2();
  })
  .then((data) => {
    res.push(data);
    return requestData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res); // [1, 2, 3] => 약 6초 소요
  })
  .catch(console.error);
```

비동기 처리가 서로 의존하지 않고 개별적으로 수행되는 경우 순차적으로 처리할 필요가 없다.
이때 Promise.all 메서드를 이용해 비동기 처리를 병렬로 처리할 수 있다.

```jsx
Promise.all([requestData1, requestData2, requestData3])
  .then(console.log) // [1, 2, 3] => 약 3초 소요
  .catch(console.error);
```

**`Promise.race`**

- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고,
  가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

- 전달받은 프로미스가 하나라도 rejected 상태가 되면 Promise.all과 동일하게 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

```jsx
Promise.race([
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 1")), 3000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 2")), 2000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 3")), 1000)
  ),
])
  .then(console.log)
  .catch(console.log); // Error: Error 3 (세 번째 프로미스가 가장 먼저 rejected 상태가 됨)
```

**`Promise.allSettled`**

전달받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환한다.
fulfilled 또는 rejected 상태와는 상관없이 모든 프로미스들의 처리 결과가 모두 담겨 있다.

처리 결과를 나타내는 객체

- fulfilled : 비동기 처리 상태를 나타내는 status / 처리 결과를 나타내는 value
- rejected : 비동기 처리 상태를 나타내는 status / 에러를 나타내는 reason

```jsx
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error!")), 1000)
  ),
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1}
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
  ]
*/
```
